### ISSUE TITLE
logo proposal

### ISSUE THREAD

**Issue by Tobaloidee** [amirkhaniansev/tyche#11]
Hi @amirkhaniansev  I am a graphic artist and would like to contribute by designing a logo for the project. If you are interested, I will begin designing asap. - [Tobaloidee](https://steemit.com/@tobaloidee)

**Comment by amirkhaniansev** [comment]
Hi @Tobaloidee. If you are willing to make it for free, we will be glad and grateful for your help.

**Comment by Tobaloidee** [comment]
Yes, it's my gift to the project as it will also benefit me by improving my portfolio..I'll show you here the initial draft when i get home tomorrow 👍😃

**Comment by Tobaloidee** [comment]
Here's what i came up with @amirkhaniansev  I hope you like it..
![INITIAL-01](https://user-images.githubusercontent.com/36028424/55277183-28d78e00-5338-11e9-852f-c1a982df0289.png)

**Comment by amirkhaniansev** [comment]
Thanks for your effort, @Tobaloidee. We definitely like the logo concept you've offered, especially the **orange** one. 
Please, create  a folder with name  **logo** in repository and add all necessary files there. I am not quite sure what files are neccessary, maybe **.svg**, **.png**. I think you know it better than me. 
And finally, create a **pull request** to have your contribution in **master**, please.

**Comment by Tobaloidee** [comment]
Hi @amirkhaniansev Here's the PR #12 with the logo upload and readme update..
Also, you can get all the color variations & formats of your new logo [HERE](https://drive.google.com/drive/u/1/folders/1W6AaVV43rsKzj-XocUCsXRczVCaYrL7_)

If you nee me in the future when it comes to logos, just mention me Sir.

Thanks and Best regards! 
- Tobaloidee

**Comment by amirkhaniansev** [comment]
I merged your pull request. Thank you for your help. I am closing this issue. Feel free to open a new one, if you any questions or offers.

**Comment by Tobaloidee** [comment]
Your are welcome! I just checked your other projects @amirkhaniansev ..I saw AccessCore and I am thinking of designing a logo for it..Are you intrerested?

**Comment by Tobaloidee** [comment]
Hi @amirkhaniansev  I made a PR again updating some alignment with the logo design. Thanks!
